config/routes.rb
Rails.application.routes.draw do  
  
  resources :users, skip: :all
  resources :clients, except: %i[index show]
  resources :businesses, except: %i[index show]
  resources :sessions, only: %i[new create destroy]
  resources :comments, only: %i[create destroy]
  resources :projects, except: %i[index edit] do
    resources :clients, only: %i[new create], shallow: true
    resources :time_entries
    resources :comments, only: %i[index], shallow: true
  end

  root 'home#front'
  
  get "/most-recently-active", to: "home#activity"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/dashboard", to: "home#dashboard"
  get "/choice", to: "home#choice"
  get "/failure", to: "sessions#failure"
  get "/login", to: "sessions#new"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :signed_in?, only: %i[dashboard]
  before_action :already_signed_in?, only: %i[front choice]
  layout "welcome_screen", only: %i[front choice activity]

  def front
  end

  def choice
  end

  def dashboard
    if !params[:search_query].blank?
      @projects = Project.search_by_title_and_user(params[:search_query], current_user)
      if @projects.blank?
        flash[:notice] = 'No Matches Found.'
        @projects = current_user.projects
      end
    else
      if params[:status] == "active"
        @projects = Project.active_projects(current_user)
      elsif params[:status] == "completed"
        @projects = Project.completed_projects(current_user)
      else
        @projects = current_user.projects
      end
    end
    
    respond_to do |f|
      f.html {render :dashboard}
      f.json {render json: @projects}
    end
  end

  def activity
    @list = User.most_recently_active
  end  
end

app/views/home/activity.html.erb
<div id="welcome-splash-mini">
    <div id="welcome-logo-mini">
        <%= link_to "penda", root_path, id: "logo-link" %>
    </div> 
</div>

<h1>The Ten Most Recently Active Users:</h1>

<ul class="list-group">
<% @list.each do |u| %>
    <li class="list-group-item"><%= u.username %>, last active at: <%= u.updated_at.strftime("%I:%M:%S %p") %></li>
<% end %>
</ul>

app/views/home/choice.html.erb
<div id="welcome-splash">
    <div id="welcome-logo">
        <%= link_to "penda", root_path, id: "logo-link" %>
        <div id="welcome-options">
            <div class="btn-group" role="group" aria-label="Button group for time entries">
                <%= button_to 'business user', new_business_path,  class: 'btn choices-btn1', method: :get %>
                <%= button_to 'standard user', new_client_path, class: 'btn choices-btn2', method: :get %>
            </div> <!-- btn-group -->
        </div> <!-- .welcome-options -->
    </div> 
</div>

app/views/home/dashboard.html.erb
<!-- <button id="js-SortAlpha" type="button" class="btn btn-secondary">Sort</button> -->

<div class="row">
    <div class="col-md-9 col-sm-9 col-6 d-flex mr-auto">
        <h3>Projects:</h3>
    </div>

    <div class="col-md-3 col-sm-3 col-6 d-flex">
    <div class="btn-group ml-auto" role="group">
        <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Status
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
            <%= link_to "Show All", dashboard_path, class: "js-AllProjects dropdown-item" %>
            <%= link_to "Active", {controller: "home", action: "dashboard", status: "active"}, class: "js-ActiveProjects dropdown-item" %>
            <%= link_to "Completed", {controller: "home", action: "dashboard", status: "completed"}, class: "js-CompletedProjects dropdown-item" %>
        </div>
    </div>
    </div>
</div>

<ul class="js-Projects list-group">
    <% if @projects.exists? %>
        <% @projects.each do |p| %>
            <li class="list-group-item"><strong>Title:</strong> <%= link_to normalized_title(p), project_path(p), "data-id": "#{p.id}" %> | <strong>Total Time:</strong> <%= p.total_hours %>  | <strong>Last Update:</strong> <%= p.last_updated %> | <strong>Status:</strong> <%= li_group_project_status(p) %></li>
        <% end %>
    <% else %>
        No current projects. Click 'New Project' to get started.
    <% end %>
</ul>

app/views/home/front.html.erb
<div id="welcome-splash">
  <div id="welcome-logo">
    <%= link_to "penda", root_path, id: "logo-link" %>
    <div class="welcome-options">
          <div class="btn-group" role="group" aria-label="Button group for time entries">
              <%= button_to 'sign up', choice_path,  class: 'js-signup btn choices-btn1', method: :get %>
              <%= button_to 'log in', login_path, class: 'js-login btn choices-btn2', method: :get %>
          </div> <!-- btn-group -->
    </div> <!-- .welcome-options -->
  </div> <!-- .welcome-logo -->
</div> <!-- .welcome-splash -->