config/routes.rb
Rails.application.routes.draw do  
  
  resources :users, skip: :all
  resources :clients, except: %i[index show]
  resources :businesses, except: %i[index show]
  resources :sessions, only: %i[new create destroy]
  resources :comments, only: %i[create destroy]
  resources :projects, except: %i[index edit] do
    resources :clients, only: %i[new create], shallow: true
    resources :time_entries
    resources :comments, only: %i[index], shallow: true
  end

  root 'home#front'
  
  get "/most-recently-active", to: "home#activity"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/dashboard", to: "home#dashboard"
  get "/choice", to: "home#choice"
  get "/failure", to: "sessions#failure"
  get "/login", to: "sessions#new"
  
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to                      :client, class_name: 'User', optional: true
    belongs_to                      :business, class_name: 'User', optional: true
    has_one                         :contract
    has_many                        :time_entries, dependent: :destroy
    has_many                        :comments, dependent: :destroy

    validates                       :title, presence: true

    accepts_nested_attributes_for   :client

    scope                           :last_five, ->(p) { where(id: p.id).first.time_entries.order("updated_at DESC").limit(5) }
    scope                           :by_active, -> { where(status: "active") }
    scope                           :user_active, ->(user) { by_active.where(business_id: user.id).or(by_active.where(client_id: user.id)).order("updated_at DESC") }
    scope                           :by_completed, -> { where(status: "completed") }
    scope                           :user_completed, ->(user) { by_completed.where(business_id: user.id).or(by_completed.where(client_id: user.id)).order("updated_at DESC") }
    scope                           :search_by_title_and_user, lambda { |query, current_user| where("client_id IS ? OR business_id IS ?", current_user.id, current_user.id).where("title LIKE ?", "%#{query}%") }

    def last_updated
        self.updated_at.strftime("%A, %d %b %Y %l:%M %p")
    end

    def find_or_build_client_by(args) #necessary in nested form for client
        result = Client.find_by(email: args[:email])
        if result 
            self.client = result
            self.client.skip_password_req = true
        else
            self.build_client(args)
            self.client.type = "Client"
            self.client.username = args[:email]
            self.client.password = Client.generated_password
            self.client.password_confirmation = self.client.password
            self.client
        end
    end

    def add_form_errors #necessary in nested form for client
        self.errors.add(:title, "cannot be blank.") if self.title.blank?
        self.client.errors.add(:first_name, "cannot be blank.") if self.client.first_name.blank?
        self.client.errors.add(:last_name, "cannot be blank.") if self.client.last_name.blank?
        self.client.errors.add(:email, "cannot be blank.") if self.client.email.blank?
    end

    def billable_hours
        self.time_entries.sum("duration").to_f
    end

    # moved from projects helper to pass through project serializer
    def total_hours
        total = self.billable_hours

        if total >= 3600
            new_total = ((total / 60) / 60).round(2)
            "#{new_total} Hours"
        elsif total >= 60 && total < 3600
            new_total = (total / 60).round(2)
            "#{new_total} Minutes"
        else
            "#{total} Seconds"
        end
    end

    def self.active_projects(current_user)
        self.by_active.user_active(current_user)
    end

    def self.completed_projects(current_user)
        self.by_completed.user_completed(current_user)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :signed_in?
    before_action :has_permission?, except: %i[index show update]
    before_action :project_owner?, only: %i[update destroy]

    def show
        @project = Project.find(params[:id])
        @comment = Comment.new

        respond_to do |f|
            f.html
            f.json {render json: @project}
        end
    end

    def new
        @project = Project.new
        @project.build_client
    end
    
    def create 
        if project_params[:client_attributes]
            if project_params[:client_attributes].values.any? {|x| x.blank?}
                @project = Project.new(project_params)
                @project.add_form_errors
                
                # render :new
                respond_to do |f|
                    f.html {render :new}
                    f.json {render json: @project}
                end
            else
                @project = Project.new
                @project.title = project_params[:title]
                @project.business_id = project_params[:business_id].to_i
                
                if business_user?
                    @project_client = @project.find_or_build_client_by(project_params[:client_attributes])
                    @project.save!
                else
                    @project.save!
                end
                flash[:notice] = "Project successfully created!"
                # redirect_to project_path(project)
                respond_to do |f|
                    f.html {redirect_to project_path(@project)}
                    f.json {render json: @project}
                end
            end
        else
            @project = Project.create(project_params)

            flash[:notice] = "Project successfully created!"
            # redirect_to project_path(project)
            respond_to do |f|
                f.html {redirect_to project_path(@project)}
                f.json {render json: @project}
            end
        end
    end

    def update
        project = Project.find(params[:id])
        project.update(status: "completed")
        
        redirect_to dashboard_path
    end

    def destroy
        @project = Project.find(params[:id])
        @project.destroy!

        flash[:notice] = "Project successfully removed."
        redirect_to dashboard_path
    end

    private

        def project_params
            params.require(:project).permit(:title, :client, :business_id, :client_id, client_attributes: [:first_name, :last_name, :email])
        end

        def project_owner?
            @project = Project.find(params[:id])
            @project.business_id == current_user.id || (@project.client_id == current_user.id && @project.business_id.nil?)
        end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    # def project_total_hours(p)
    #     total = p.billable_hours

    #     if total >= 3600
    #         new_total = ((total / 60) / 60).round(2)
    #         "#{new_total} Hours"
    #     elsif total >= 60 && total < 3600
    #         new_total = (total / 60).round(2)
    #         "#{new_total} Minutes"
    #     else
    #         "#{total} Seconds"
    #     end
    # end
    def normalized_title(project)
        project.title.split.map(&:capitalize).join(' ')
    end

    def latest_entries
        Project.last_five(@project)
    end

    def permitted_to_take_action?
        (@project.business_id && current_user.type == "Business") || (@project.business_id.nil? && current_user.type == "Client")
    end

    def recent_comments
        Comment.last_ten_comments(@project)
    end

    def professional_use?
        business_user? || @project.business_id
    end

    def business_full_name
        @project.business.full_name
    end

    def client_full_name
        @project.client.full_name
    end

    def project_has_time_entries?
        @project.time_entries.exists?
    end

    def project_has_comments?
        @project.comments.exists?
    end

    def li_group_project_status(p)
        p.status.capitalize
    end
end

app/views/projects/new.html.erb
<div id="js-ProjectNewForm">
  <h1>Create a New Project</h1>

  <%= form_for @project, class: "was-validated" do |f| %>
      <% if business_user? %>
        <%= f.hidden_field :business_id, :value => current_user.id %>
      <% else %>
        <%= f.hidden_field :client_id, :value => current_user.id %>
      <% end %>

      <% if @project.errors.any? || @project.client.errors.any? %>
          <div id="error_explanation">
            <h2> Oops! Looks like something was missing. </h2>
            <ul>
                  <% @project.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
    
                  <% @project.client.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
            </ul>
          </div>
      <% end %>
      
      <div class="form-row">
        <div class="form-group col-md-8">
          <%= f.label :title, "Title:" %>
          <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "form-control" %>
        </div>
      </div>
    
      <% if has_permission? %>
        <p>Client Information:</p>
        <%= f.fields_for :client do |c| %>
          <div class="form-row">
            <div class="form-group col-md-4">
              <%= c.label :first_name %>
              <%= c.text_field :first_name, autofocus: true, autocomplete: "title", class: "form-control" %>
            </div> 

            <div class="form-group col-md-4">
              <%= c.label :last_name %>
              <%= c.text_field :last_name, autofocus: true, autocomplete: "title", class: "form-control" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-8">
              <%= c.label :email %>
              <%= c.email_field :email, autofocus: true, autocomplete: "title", class: "form-control" %>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="actions">
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>

  <% end %>
</div>

app/views/projects/show.html.erb
<h1><%= normalized_title(@project) %></h1>

<% if professional_use? %>
    <p>
    <strong>Business:</strong> <%= business_full_name %><br>
    <strong>Client:</strong> <%= client_full_name %><br>
    <strong>Total Billable Time:</strong> <%= @project.total_hours %>
    <p>
<% else %>
    <p><strong>Total Time:</strong> <%= @project.total_hours %></p>
<% end %>

<h2>Time Entries:</h2>

<p>Displaying the five most recent entries:</p>

<ul class="list-group">
    <% if project_has_time_entries? %> 
        <% latest_entries.each do |t| %> 
            <li class="list-group-item"><strong>Title:</strong> <%= link_to t.title, project_time_entry_path(@project, t), class: "js-ShowTE" %> | <strong>Duration:</strong> <%= time_duration(t) %> | <strong>Created:</strong> <%= t.created_at.strftime("%A, %d %b %Y %l:%M %p") %></li>
        <% end %>
    <% else %>
        No recorded time entries. 
    <% end %>
</ul>

<br>
<% if permitted_to_take_action? %>
    <div class="te-display-group">
        <div class="btn-group" role="group" aria-label="Button group for time entries">
            <%= button_to 'Add New Entry', new_project_time_entry_path(@project), class: 'js-NewTimeEntry btn btn-primary', method: :get %>
            <%= button_to 'All Time Entries', project_time_entries_path(@project), class: 'js-AllTimeEntries btn btn-secondary', method: :get %>
        </div> <!-- .btn-group -->
    </div> <!-- .te-display-group -->
<% else %>
    <%= button_to 'All Time Entries', project_time_entries_path(@project), class: 'btn btn-secondary', method: :get %>
<% end %>

<h2>Conversation History:</h2>

<!-- <%= link_to "Load Comments", project_comments_path(@project), class: "load-comments" %> -->

<ul class="list-group" id="comment-list">
    <% if project_has_comments? %> 
        <% recent_comments.each do |c| %> <!-- see projects helper -->
            <% if c.user == current_user %>
                <li class="list-group-item"><strong><%= c.user.username %></strong> says: <%= c.content %> | <strong>Posted at:</strong> <%= c.time_created %> <%= link_to "X", comment_path(c), data: { confirm: "Are you sure?", id: c.id }, method: :delete, class: "js-Delete btn-sm btn-danger pull-right buttonJS" %></li>
            <% else %>
                <li class="list-group-item"><strong><%= c.user.username %></strong> says: <%= c.content %> | <strong>Posted at:</strong> <%= c.time_created %></li>
            <% end %>
        <% end %>
    <% else %>
        No comments yet. 
    <% end %>
</ul>

<p><%= button_to 'All Comments', project_comments_path(@project), class: 'btn btn-secondary', method: :get %><p>

<h2>Join the Conversation:</h2>

<p><%= render partial: 'comments/comment', locals: {comment: @comment} %></p>

<% if permitted_to_take_action? %>
    <div class="te-display-group">
        <div class="btn-group" role="group" aria-label="Button group for project status">
            <p><%= button_to 'Mark Project Completed', project_path(@project), data: { confirm: "Are you sure?" }, class: 'btn btn-danger', method: :patch %><p>
        </div> <!-- btn-group -->
    </div> <!-- row -->
<% end %>

<br>

<% if permitted_to_take_action? %>
    <h3>Delete Project</h3>

    Warning! This cannot be undone.

    <p><%= button_to "Delete This Project", project_path(@project), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %></p>
<% end %>