config/routes.rb
Rails.application.routes.draw do  
  
  resources :users, skip: :all
  resources :clients, except: %i[index show]
  resources :businesses, except: %i[index show]
  resources :sessions, only: %i[new create destroy]
  resources :comments, only: %i[create destroy]
  resources :projects, except: %i[index edit] do
    resources :clients, only: %i[new create], shallow: true
    resources :time_entries
    resources :comments, only: %i[index], shallow: true
  end

  root 'home#front'
  
  get "/most-recently-active", to: "home#activity"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/dashboard", to: "home#dashboard"
  get "/choice", to: "home#choice"
  get "/failure", to: "sessions#failure"
  get "/login", to: "sessions#new"
  
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to  :project
  belongs_to  :user

  validates   :title, presence: true
  validates   :content, presence: true
  validates   :start_time, presence: true, allow_blank: false
  validates   :end_time, presence: true, allow_blank: false

  def total_time
    start_time = self.start_time.to_f    
    end_time = self.end_time.to_f
    total = ((end_time - start_time)).round(2).to_f
  end

  def true_start_time
    self.start_time.strftime("%A, %d %b %Y %l:%M %p")
  end

  def true_end_time
    self.end_time.strftime("%A, %d %b %Y %l:%M %p")
  end

  def self.new_from_params(params)
    time_entry = self.new(params).tap do |u|
        u.end_time = Time.zone.now
        u.duration = u.total_time
        u.finished = true
    end
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
    before_action :signed_in?
    before_action :is_resource_owner?, only: %i[edit update destroy]

    def index
        @project = Project.find(params[:project_id])
        respond_to do |f|
            f.html
            f.json {render json: @project}
        end
    end

    def show
        @project = Project.find(params[:project_id])
        @time_entry = TimeEntry.find(params[:id])
    end
    
    def new
        project = Project.find(params[:project_id])
        @time_entry = project.time_entries.build
    end

    def create
        @time_entry = TimeEntry.new_from_params(time_entry_params)
        if @time_entry.save
            flash[:notice] = "Entry Successfully Added."
            redirect_to project_path(@time_entry.project)
        else
            render :new
        end
    end

    def edit
        @project = Project.find(params[:project_id])
        @time_entry = TimeEntry.find(params[:id])
    end

    def update
        @time_entry = TimeEntry.find(params[:id])
        @time_entry.assign_attributes(time_entry_params)
        if @time_entry.valid?
            @time_entry.update(time_entry_params)
            @time_entry.duration = @time_entry.total_time
            @time_entry.save

            redirect_to project_path(@time_entry.project)
        else
            render :edit
        end
    end

    def destroy
        time_entry = TimeEntry.find(params[:id])
        time_entry.destroy

        flash[:notice] = "Time entry was successfully removed."
        redirect_to project_path(params[:project_id])
    end

    private

    def time_entry_params
        params.require(:time_entry).permit(:project_id, :user_id, :title, :start_time, :end_time, :duration, :content)
    end

end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
    def time_duration(time)
        total = time.duration.to_f

        if total >= 3600
            new_total = ((total / 60) / 60).round(2)
            "#{new_total} Hours"
        elsif total >= 60 && total < 3600
            new_total = (total / 60).round(2)
            "#{new_total} Minutes"
        else
            "#{total} Seconds"
        end
    end

    def current_time
        Time.zone.now.strftime("%I:%M:%S %p")
    end

    def normalized_start
        @time_entry.start_time.strftime("%I:%M:%S %p") unless @time_entry.start_time.nil?
    end

    def normalized_end
        @time_entry.end_time.strftime("%I:%M:%S %p") unless @time_entry.end_time.nil?
    end

    def current_user_created?
        @time_entry.user_id == current_user.id
    end
end

app/views/time_entries/_time_entry.html.erb
<%= form_for [time_entry.project, time_entry], class: "was-validated" do |f| %>
    <% if time_entry.errors.any? %>
        <div id="error_explanation">
          <h2> Oops! Looks like something was missing. </h2>
          <ul>
            <% time_entry.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.hidden_field :project_id, :value => time_entry.project.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>

    <div class="form-row">
        <div class="form-group col-md-6">
            <%= f.label :title, "Title:" %><br>
            <%= f.text_field :title, class: "form-control" %>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <%= f.label :start_time, "Start Time:" %><br>
            <%= f.text_field :start_time, value: current_time, autofocus: true, autocomplete: "start time", class: "form-control" %>
        </div>
    </div>

    <!-- proper stopwatch functionality will be added with JS at a later point -->
    <!-- <div class="field-with-errors"> --> 
    <!-- <%= f.label :end_time, "End Time:" %><br> -->
    <!-- <%= f.text_field :end_time, autofocus: true, autocomplete: "end_time" %> -->
    <!-- </div> -->

    <div class="form-row">
        <div class="form-group col-md-6">
            <%= f.label :content, "What was completed?" %><br>
            <%= f.text_area :content, autofocues: true, class: "form-control" %>
        </div>
    </div>

    <%= f.submit "End Time", class: "btn btn-primary" %>
<% end %>

app/views/time_entries/edit.html.erb
<h1>Editing <%= @time_entry.project.title %></h1>

<%= form_for [@time_entry.project, @time_entry], class: "was-validated" do |f| %>
    <% if @time_entry.errors.any? %>
        <div id="error_explanation">
          <h2> Oops! Looks like something was missing. </h2>
          <ul>
            <% @time_entry.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.hidden_field :project_id, :value => @time_entry.project.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>

    <div class="form-row">
        <div class="form-group col-md-6">
            <%= f.label :title, "Title:" %><br>
            <%= f.text_field :title, class: "form-control" %>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <%= f.label :start_time, "Start Time:" %><br>
            <%= f.text_field :start_time, value: normalized_start,  autofocus: true, autocomplete: "start time", class: "form-control" %>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <%= f.label :end_time, "End Time:" %><br>
            <%= f.text_field :end_time, value: normalized_end, autofocus: true, autocomplete: "end_time", class: "form-control" %>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <%= f.label :content, "What was completed?" %><br>
            <%= f.text_area :content, autofocus: true, class: "form-control" %>
        </div>
    </div>

    <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

<h3>Delete Entry</h3>

Warning! This cannot be undone.

<p><%= button_to "Delete This Entry", project_time_entry_path(@time_entry.project, @time_entry), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %></p>

app/views/time_entries/index.html.erb
<h1>Displaying All Time Entries for <%= @project.title %>:</h1>

<ul class="list-group">
    <% if @project.time_entries != [] %>
        <% @project.time_entries.each do |t| %>
            <li class="list-group-item"><strong>Title:</strong> <%= link_to t.title, project_time_entry_path(@project, t) %> | <strong>Duration:</strong> <%= time_duration(t) %> | <strong>Created:</strong> <%= t.created_at.strftime("%A, %d %b %Y %l:%M %p") %></li>
        <% end %>
    <% else %>
        No recorded time entries. Click 'Add New Entry' to get started.
    <% end %>
</ul>

app/views/time_entries/new.html.erb
<h1>Adding a New Time Entry for <%= @time_entry.project.title %></h1>

<div class="clock"></div><br>

<%= render partial: 'time_entry', locals: {time_entry: @time_entry} %>

app/views/time_entries/show.html.erb
<div id="js-teCard">
    <h1>Displaying Time Entry:</h1>

    <div class="row">
        <div class="col-lg-6 col-md-10 col-sm-10 col-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Title: <%= @time_entry.title %></h5>
                    <h6 class="card-subtitle mb-2 text-muted">Total Duration: <%= time_duration(@time_entry) %></h6>
                    <p class="card-text">Description: <%= @time_entry.content %></p>
                    <p class="card-text">Start Time: <%= @time_entry.start_time.strftime("%A, %d %b %Y %l:%M %p") %></p>
                    <p class="card-text">End Time: <%= @time_entry.end_time.strftime("%A, %d %b %Y %l:%M %p") %></p> 
                </div>
            </div>
        </div>
    </div>

    <br>
</div>

<div class="js-teOptions">
    <% if current_user_created? %>
    <p><%= link_to "Edit This Entry", edit_project_time_entry_path(@time_entry.project, @time_entry), class: "btn btn-secondary" %></p>
    <% end %>
    <p><%= link_to "Back to Project", project_path(@project), class: "btn btn-secondary" %></p>
</div>