config/routes.rb
Rails.application.routes.draw do  
  
  resources :users, skip: :all
  resources :clients, except: %i[index show]
  resources :businesses, except: %i[index show]
  resources :sessions, only: %i[new create destroy]
  resources :comments, only: %i[create destroy]
  resources :projects, except: %i[index edit] do
    resources :clients, only: %i[new create], shallow: true
    resources :time_entries
    resources :comments, only: %i[index], shallow: true
  end

  root 'home#front'
  
  get "/most-recently-active", to: "home#activity"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/dashboard", to: "home#dashboard"
  get "/choice", to: "home#choice"
  get "/failure", to: "sessions#failure"
  get "/login", to: "sessions#new"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
  <head>
    <title>PendaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag asset_path('favicon (3).ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=BioRhyme|Black+Ops+One|Bungee|Bungee+Shade|Creepster|Ewert|Fruktur|Gravitas+One|Monoton|Rubik:900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alegreya|Alegreya+Sans|Merriweather|Merriweather+Sans|Nunito|Nunito+Sans|Quattrocento|Quattrocento+Sans|Roboto|Roboto+Mono|Roboto+Slab" rel="stylesheet">

    <script type="text/javascript">
      if (window.location.hash && window.location.hash == '#_=_') { window.location.hash = ''; }
    </script>
  </head>

  <body>

    <nav class="navbar fixed-top navbar-dark bg-dark custom-nav-font navbar-expand-sm">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to image_tag("favicon-256.png", width: "30", height: "30", alt: ""), dashboard_path, class: "d-inline-block align-top" %> 
          <span class= "nav-welcome-logo">penda</span>
        </div> <!-- .navbar-header -->

        <button class="navbar-toggler navbar-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <%= form_tag(dashboard_path, method: :get, class: "form-inline") do %>
              <li><%= text_field_tag :search_query, params[:search_query], placeholder: "Project Name...", class: "form-control mr-sm-2"  %>
              <%= submit_tag 'Search', name: nil, class: "btn-sm btn-outline-secondary" %> </li>
            <% end %>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Projects
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "All Projects", dashboard_path, class: "dropdown-item" %>
                <%= link_to "New Project", new_project_path, class: "js-NewProject dropdown-item" %>
              </div>
            </li>

            <% if business_signed_in? %> <!-- options for busienss user -->

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.username %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to 'Edit profile', edit_business_path(current_user), class: 'dropdown-item' %>
                  <%= link_to "Log Out", session_path(current_user), method: :delete, class: 'dropdown-item' %>
                </div>
              </li>
          
            <% else %>  <!-- options for client user -->

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.username %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to 'Edit Profile', edit_client_path(current_user), class: 'dropdown-item' %>
                  <%= link_to 'Log Out', session_path(current_user), method: :delete, :class => 'dropdown-item' %>
                </div>
              </li>

            <% end %>
          </ul>
        </div> <!-- .nav collapse -->
      </div> <!-- .container-fluid -->
    </nav> <!-- .navbar -->

    <div class="container">
      <div class=""row align-items-center">
        <div class="col-12 mx-auto text-center flash-box">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      </div>
    </div>

    <div class="js-Content container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/welcome_screen.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
  <head>
    <title>PendaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag asset_path('favicon (3).ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=BioRhyme|Black+Ops+One|Bungee|Bungee+Shade|Creepster|Ewert|Fruktur|Gravitas+One|Monoton|Rubik:900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alegreya|Alegreya+Sans|Merriweather|Merriweather+Sans|Nunito|Nunito+Sans|Quattrocento|Quattrocento+Sans|Roboto|Roboto+Mono|Roboto+Slab" rel="stylesheet">

    <script type="text/javascript">
      if (window.location.hash && window.location.hash == '#_=_') { window.location.hash = ''; }
    </script>
  </head>

  <body>

  <div class="container">
    <div class=""row align-items-center">
      <div class="col-12 mx-auto text-center flash-box">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>
  </div>

    <div class="container h-100">
      <div class="row align-items-center h-100">
        <div class="col-12 mx-auto text-center">
          <section id="js-ContentBox">
            <%= yield %>
          </section>
        </div> <!-- .col --> 
      </div> <!-- .row -->
    </div> <!-- .container -->
    
  </body>
</html>